### ISSUE TITLE
Method User  Object Page

### ISSUE THREAD

**Issue by bolom** [LordAlexWorks/documentation-api#7]
![capture d ecran 4](https://cloud.githubusercontent.com/assets/72155/7989607/b4a14e02-0ab8-11e5-9acb-a68e2f22d9e8.png)

**Comment by accetone** [comment]
I'm added css class "with-answer". You should use it when want example displayed with docs (as on screenshot http://clip2net.com/s/3iPEuef)

https://github.com/LordAlexWorks/documentation-api/commit/2c672ac3c53cc39455cb8c5f9e03843f87a57e0d

**Comment by bolom** [comment]
@accetone it's not a css problem but a Js. it's the method tocify who should be fixed
